#!/bin/sh

exec xidlehook --not-when-audio --not-when-fullscreen --detect-sleep --timer 300 "betterlockscreen -l dim" - & 
exec xidlehook --not-when-audio --not-when-fullscreen --timer 420 "systemctl suspend" - 
