#!/usr/bin/env bash

declare -A options=(
    [Brave]=https://search.brave.com/search?q=
    [Google]=https://www.google.com/search?q=
    [DuckDuckGo]=https://duckduckgo.com/?q=
    [YouTube]=https://www.youtube.com/results?search_query=
    [Goodreads]=https://www.goodreads.com/search?q=
    [GitHub]=https://github.com/search?q=
    [Wikidata]=https://www.wikidata.org/w/index.php?search=
    [Wikipedia]=https://en.wikipedia.org/w/index.php?search=
    [Z-Library]=https://1lib.in/s/
    [Bing]=https://www.bing.com/images/search?q=
    [Wallpaperflare]=https://www.wallpaperflare.com/search?wallpaper=
)

choice=$(printf "%s\n" "${!options[@]}" | rofi -dmenu -i -l 20 -p "Choose Search") || exit 1

if [ "$choice" ]
then
    query=$(rofi -dmenu -i -l 20 -p "Query $choice") || exit 1
fi
engineurl=${options["$choice"]}

xdg-open "$engineurl""$query" &
